#!/usr/bin/env bash
# g1_lidar_one_time_setup_pc2.sh
#
# One-time setup/check script for viewing the Unitree G1 EDU MID-360 LiDAR
# from PC2 using ROS 2 Foxy + Unitree CycloneDDS + RViz over ssh -Y.
#
# Safe to re-run. It does not overwrite Unitree's setup.sh; instead it creates:
#   ~/.g1_lidar_env.sh
#   ~/bin/g1_lidar_rviz.sh
#
# Optional overrides:
#   G1_IFACE=eth0 ./g1_lidar_one_time_setup_pc2.sh
#   UNITREE_ROS2_DIR=$HOME/unitree_ros2 ./g1_lidar_one_time_setup_pc2.sh
#   G1_LIDAR_TOPIC=/utlidar/cloud ./g1_lidar_one_time_setup_pc2.sh
#   G1_LIDAR_FRAME=livox_frame ./g1_lidar_one_time_setup_pc2.sh

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_LAUNCHER="$SCRIPT_DIR/g1_lidar_rviz.sh"
UNITREE_ROS2_DIR="${UNITREE_ROS2_DIR:-$HOME/unitree_ros2}"
ROS_DISTRO_NAME="${ROS_DISTRO_NAME:-foxy}"
LIDAR_TOPIC="${G1_LIDAR_TOPIC:-/utlidar/cloud_livox_mid360}"
LIDAR_FRAME="${G1_LIDAR_FRAME:-livox_frame}"
MAP_FRAME="${G1_MAP_FRAME:-map}"
ENV_FILE="$HOME/.g1_lidar_env.sh"
BIN_DIR="$HOME/bin"
LAUNCH_SCRIPT="$BIN_DIR/g1_lidar_rviz.sh"

log()  { printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
info() { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

source_relaxed() {
  local had_nounset=0
  [[ $- == *u* ]] && had_nounset=1
  set +u
  # shellcheck disable=SC1090
  source "$1"
  (( had_nounset )) && set -u
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

sudo_apt_install_missing() {
  local pkgs=("$@")
  local missing=()

  for p in "${pkgs[@]}"; do
    if ! dpkg -s "$p" >/dev/null 2>&1; then
      missing+=("$p")
    fi
  done

  if (( ${#missing[@]} == 0 )); then
    log "All apt packages already installed."
    return 0
  fi

  info "Installing missing apt packages: ${missing[*]}"
  sudo apt-get update
  sudo apt-get install -y "${missing[@]}"
}

detect_iface() {
  # Prefer an interface that already has a 192.168.123.x address.
  local iface
  iface="$(ip -o -4 addr show scope global 2>/dev/null \
    | awk '$4 ~ /^192\.168\.123\./ {print $2; exit}')"
  if [[ -n "${iface:-}" ]]; then
    echo "$iface"
    return 0
  fi

  # Next, ask Linux which interface it would use for the G1/LiDAR subnet.
  iface="$(ip route get 192.168.123.120 2>/dev/null \
    | awk '{for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')"
  if [[ -n "${iface:-}" && "$iface" != "lo" ]]; then
    echo "$iface"
    return 0
  fi

  # Last, pick the first non-loopback interface that is up.
  iface="$(ip -o link show up 2>/dev/null \
    | awk -F': ' '$2 != "lo" {print $2; exit}')"
  if [[ -n "${iface:-}" ]]; then
    echo "$iface"
    return 0
  fi

  return 1
}

ensure_unitree_ros2_present() {
  if [[ -d "$UNITREE_ROS2_DIR" ]]; then
    log "Found Unitree ROS2 directory: $UNITREE_ROS2_DIR"
    return 0
  fi

  warn "Unitree ROS2 directory not found: $UNITREE_ROS2_DIR"
  info "Cloning official unitree_ros2 into $UNITREE_ROS2_DIR"
  git clone https://github.com/unitreerobotics/unitree_ros2 "$UNITREE_ROS2_DIR"
}

maybe_build_unitree_ws() {
  local ws="$UNITREE_ROS2_DIR/cyclonedds_ws"
  local setup="$ws/install/setup.bash"

  if [[ -f "$setup" ]]; then
    log "Found Unitree CycloneDDS workspace install: $setup"
    return 0
  fi

  warn "Missing $setup"
  warn "The script can try to build it, but this may take a while and may fail if ROS apt sources are not configured."

  [[ -d "$ws/src" ]] || die "Missing $ws/src. Check your unitree_ros2 checkout."

  sudo_apt_install_missing \
    python3-colcon-common-extensions \
    ros-"$ROS_DISTRO_NAME"-rmw-cyclonedds-cpp \
    ros-"$ROS_DISTRO_NAME"-rosidl-generator-dds-idl \
    libyaml-cpp-dev

  pushd "$ws/src" >/dev/null

  if [[ ! -d rmw_cyclonedds ]]; then
    info "Cloning rmw_cyclonedds branch $ROS_DISTRO_NAME"
    git clone https://github.com/ros2/rmw_cyclonedds -b "$ROS_DISTRO_NAME"
  else
    log "rmw_cyclonedds already exists."
  fi

  if [[ ! -d cyclonedds ]]; then
    info "Cloning cyclonedds releases/0.10.x"
    git clone https://github.com/eclipse-cyclonedds/cyclonedds -b releases/0.10.x
  else
    log "cyclonedds already exists."
  fi

  popd >/dev/null

  pushd "$ws" >/dev/null

  info "Building cyclonedds first."
  export LD_LIBRARY_PATH="/opt/ros/$ROS_DISTRO_NAME/lib:${LD_LIBRARY_PATH:-}"
  colcon build --packages-select cyclonedds

  info "Building remaining Unitree ROS2 packages."
  source_relaxed "/opt/ros/$ROS_DISTRO_NAME/setup.bash"
  colcon build

  popd >/dev/null

  [[ -f "$setup" ]] || die "Build finished but $setup still does not exist."
  log "Built Unitree CycloneDDS workspace."
}

write_env_file() {
  local iface="$1"

  info "Writing $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
#!/usr/bin/env bash
# Auto-generated by g1_lidar_one_time_setup_pc2.sh
# Source this before using ROS2/RViz for the G1 LiDAR.

# Avoid Conda/Qt environment variables breaking RViz plugin loading.
unset QT_PLUGIN_PATH
unset QT_QPA_PLATFORM_PLUGIN_PATH

__g1_had_nounset=0
[[ \$- == *u* ]] && __g1_had_nounset=1
set +u
source /opt/ros/$ROS_DISTRO_NAME/setup.bash
source "$UNITREE_ROS2_DIR/cyclonedds_ws/install/setup.bash"
(( __g1_had_nounset )) && set -u
unset __g1_had_nounset

export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export ROS_LOCALHOST_ONLY=0

# Unitree official setup.sh uses a CycloneDDS interface-specific XML block.
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><Interfaces><NetworkInterface name="$iface" priority="default" multicast="default" /></Interfaces></General></Domain></CycloneDDS>'

# Default Unitree/G1 lidar topic/frame. Override before launching if needed.
export G1_LIDAR_TOPIC="\${G1_LIDAR_TOPIC:-$LIDAR_TOPIC}"
export G1_LIDAR_FRAME="\${G1_LIDAR_FRAME:-$LIDAR_FRAME}"
export G1_MAP_FRAME="\${G1_MAP_FRAME:-$MAP_FRAME}"

# Unitree usually uses DDS domain 0/default here.
# Set G1_ROS_DOMAIN_ID explicitly if your robot uses a different domain.
if [[ -n "\${G1_ROS_DOMAIN_ID:-}" ]]; then
  export ROS_DOMAIN_ID="\$G1_ROS_DOMAIN_ID"
else
  unset ROS_DOMAIN_ID
fi
EOF

  chmod +x "$ENV_FILE"
  log "Created $ENV_FILE using interface: $iface"
}

write_launcher() {
  mkdir -p "$BIN_DIR"

  [[ -f "$REPO_LAUNCHER" ]] || die "Missing repo launcher: $REPO_LAUNCHER"

  info "Installing $REPO_LAUNCHER -> $LAUNCH_SCRIPT"
  install -m 0755 "$REPO_LAUNCHER" "$LAUNCH_SCRIPT"
  log "Installed $LAUNCH_SCRIPT"
}

main() {
  info "G1 LiDAR one-time setup/check for PC2"

  need_cmd ip
  need_cmd awk
  need_cmd grep

  if [[ ! -f "/opt/ros/$ROS_DISTRO_NAME/setup.bash" ]]; then
    die "ROS 2 $ROS_DISTRO_NAME not found at /opt/ros/$ROS_DISTRO_NAME/setup.bash. Install ROS Foxy first."
  fi

  sudo_apt_install_missing \
    git curl xauth x11-apps mesa-utils \
    ros-"$ROS_DISTRO_NAME"-rviz2 \
    ros-"$ROS_DISTRO_NAME"-rviz-common \
    ros-"$ROS_DISTRO_NAME"-rviz-default-plugins \
    ros-"$ROS_DISTRO_NAME"-rviz-ogre-vendor \
    ros-"$ROS_DISTRO_NAME"-tf2-ros \
    ros-"$ROS_DISTRO_NAME"-rmw-cyclonedds-cpp \
    ros-"$ROS_DISTRO_NAME"-rosidl-generator-dds-idl \
    python3-colcon-common-extensions \
    libyaml-cpp-dev

  ensure_unitree_ros2_present
  maybe_build_unitree_ws

  local iface="${G1_IFACE:-}"
  if [[ -z "$iface" ]]; then
    iface="$(detect_iface || true)"
  fi

  if [[ -z "$iface" ]]; then
    die "Could not detect robot network interface. Re-run with G1_IFACE=<interface>, e.g. G1_IFACE=eth0 $0"
  fi

  info "Using network interface: $iface"
  ip -o -4 addr show "$iface" || true

  write_env_file "$iface"
  write_launcher

  # Basic validation.
  # shellcheck disable=SC1090
  source_relaxed "$ENV_FILE"

  log "Environment check:"
  echo "  RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-}"
  echo "  CYCLONEDDS_URI=$CYCLONEDDS_URI"
  echo "  G1_LIDAR_TOPIC=$G1_LIDAR_TOPIC"
  echo "  G1_LIDAR_FRAME=$G1_LIDAR_FRAME"

  echo
  info "Current LiDAR/cloud topics visible from this shell:"
  ros2 daemon stop >/dev/null 2>&1 || true
  ros2 daemon start >/dev/null 2>&1 || true
  sleep 2
  ros2 topic list 2>/dev/null | grep -E 'utlidar|livox|cloud|imu' || warn "No lidar/cloud topics discovered yet."

  echo
  log "Done."
  echo "Next time, after ssh -Y into PC2, run:"
  echo "  ~/bin/g1_lidar_rviz.sh"
}

main "$@"
