#!/usr/bin/env bash
# g1_lidar_one_time_setup_pc2.sh
#
# One-time setup/check script for viewing the Unitree G1 EDU MID-360 LiDAR
# from PC2 using ROS 2 Foxy + Unitree CycloneDDS + RViz over ssh -Y.
#
# Safe to re-run. It does not overwrite Unitree's setup.sh; instead it creates:
#   ~/.g1_lidar_env.sh
#   ~/bin/g1_lidar_rviz.sh
#
# Optional overrides:
#   G1_IFACE=eth0 ./g1_lidar_one_time_setup_pc2.sh
#   UNITREE_ROS2_DIR=$HOME/unitree_ros2 ./g1_lidar_one_time_setup_pc2.sh
#   G1_LIDAR_TOPIC=/utlidar/cloud ./g1_lidar_one_time_setup_pc2.sh
#   G1_LIDAR_FRAME=livox_frame ./g1_lidar_one_time_setup_pc2.sh

set -Eeuo pipefail

UNITREE_ROS2_DIR="${UNITREE_ROS2_DIR:-$HOME/unitree_ros2}"
ROS_DISTRO_NAME="${ROS_DISTRO_NAME:-foxy}"
LIDAR_TOPIC="${G1_LIDAR_TOPIC:-/utlidar/cloud_livox_mid360}"
LIDAR_FRAME="${G1_LIDAR_FRAME:-livox_frame}"
MAP_FRAME="${G1_MAP_FRAME:-map}"
ENV_FILE="$HOME/.g1_lidar_env.sh"
BIN_DIR="$HOME/bin"
LAUNCH_SCRIPT="$BIN_DIR/g1_lidar_rviz.sh"

log()  { printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
info() { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

source_relaxed() {
  local had_nounset=0
  [[ $- == *u* ]] && had_nounset=1
  set +u
  # shellcheck disable=SC1090
  source "$1"
  (( had_nounset )) && set -u
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

sudo_apt_install_missing() {
  local pkgs=("$@")
  local missing=()

  for p in "${pkgs[@]}"; do
    if ! dpkg -s "$p" >/dev/null 2>&1; then
      missing+=("$p")
    fi
  done

  if (( ${#missing[@]} == 0 )); then
    log "All apt packages already installed."
    return 0
  fi

  info "Installing missing apt packages: ${missing[*]}"
  sudo apt-get update
  sudo apt-get install -y "${missing[@]}"
}

detect_iface() {
  # Prefer an interface that already has a 192.168.123.x address.
  local iface
  iface="$(ip -o -4 addr show scope global 2>/dev/null \
    | awk '$4 ~ /^192\.168\.123\./ {print $2; exit}')"
  if [[ -n "${iface:-}" ]]; then
    echo "$iface"
    return 0
  fi

  # Next, ask Linux which interface it would use for the G1/LiDAR subnet.
  iface="$(ip route get 192.168.123.120 2>/dev/null \
    | awk '{for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')"
  if [[ -n "${iface:-}" && "$iface" != "lo" ]]; then
    echo "$iface"
    return 0
  fi

  # Last, pick the first non-loopback interface that is up.
  iface="$(ip -o link show up 2>/dev/null \
    | awk -F': ' '$2 != "lo" {print $2; exit}')"
  if [[ -n "${iface:-}" ]]; then
    echo "$iface"
    return 0
  fi

  return 1
}

ensure_unitree_ros2_present() {
  if [[ -d "$UNITREE_ROS2_DIR" ]]; then
    log "Found Unitree ROS2 directory: $UNITREE_ROS2_DIR"
    return 0
  fi

  warn "Unitree ROS2 directory not found: $UNITREE_ROS2_DIR"
  info "Cloning official unitree_ros2 into $UNITREE_ROS2_DIR"
  git clone https://github.com/unitreerobotics/unitree_ros2 "$UNITREE_ROS2_DIR"
}

maybe_build_unitree_ws() {
  local ws="$UNITREE_ROS2_DIR/cyclonedds_ws"
  local setup="$ws/install/setup.bash"

  if [[ -f "$setup" ]]; then
    log "Found Unitree CycloneDDS workspace install: $setup"
    return 0
  fi

  warn "Missing $setup"
  warn "The script can try to build it, but this may take a while and may fail if ROS apt sources are not configured."

  [[ -d "$ws/src" ]] || die "Missing $ws/src. Check your unitree_ros2 checkout."

  sudo_apt_install_missing \
    python3-colcon-common-extensions \
    ros-"$ROS_DISTRO_NAME"-rmw-cyclonedds-cpp \
    ros-"$ROS_DISTRO_NAME"-rosidl-generator-dds-idl \
    libyaml-cpp-dev

  pushd "$ws/src" >/dev/null

  if [[ ! -d rmw_cyclonedds ]]; then
    info "Cloning rmw_cyclonedds branch $ROS_DISTRO_NAME"
    git clone https://github.com/ros2/rmw_cyclonedds -b "$ROS_DISTRO_NAME"
  else
    log "rmw_cyclonedds already exists."
  fi

  if [[ ! -d cyclonedds ]]; then
    info "Cloning cyclonedds releases/0.10.x"
    git clone https://github.com/eclipse-cyclonedds/cyclonedds -b releases/0.10.x
  else
    log "cyclonedds already exists."
  fi

  popd >/dev/null

  pushd "$ws" >/dev/null

  info "Building cyclonedds first."
  export LD_LIBRARY_PATH="/opt/ros/$ROS_DISTRO_NAME/lib:${LD_LIBRARY_PATH:-}"
  colcon build --packages-select cyclonedds

  info "Building remaining Unitree ROS2 packages."
  source_relaxed "/opt/ros/$ROS_DISTRO_NAME/setup.bash"
  colcon build

  popd >/dev/null

  [[ -f "$setup" ]] || die "Build finished but $setup still does not exist."
  log "Built Unitree CycloneDDS workspace."
}

write_env_file() {
  local iface="$1"

  info "Writing $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
#!/usr/bin/env bash
# Auto-generated by g1_lidar_one_time_setup_pc2.sh
# Source this before using ROS2/RViz for the G1 LiDAR.

# Avoid Conda/Qt environment variables breaking RViz plugin loading.
unset QT_PLUGIN_PATH
unset QT_QPA_PLATFORM_PLUGIN_PATH

__g1_had_nounset=0
[[ \$- == *u* ]] && __g1_had_nounset=1
set +u
source /opt/ros/$ROS_DISTRO_NAME/setup.bash
source "$UNITREE_ROS2_DIR/cyclonedds_ws/install/setup.bash"
(( __g1_had_nounset )) && set -u
unset __g1_had_nounset

export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export ROS_LOCALHOST_ONLY=0

# Unitree official setup.sh uses a CycloneDDS interface-specific XML block.
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><Interfaces><NetworkInterface name="$iface" priority="default" multicast="default" /></Interfaces></General></Domain></CycloneDDS>'

# Default Unitree/G1 lidar topic/frame. Override before launching if needed.
export G1_LIDAR_TOPIC="\${G1_LIDAR_TOPIC:-$LIDAR_TOPIC}"
export G1_LIDAR_FRAME="\${G1_LIDAR_FRAME:-$LIDAR_FRAME}"
export G1_MAP_FRAME="\${G1_MAP_FRAME:-$MAP_FRAME}"

# Unitree usually uses DDS domain 0/default here.
# Set G1_ROS_DOMAIN_ID explicitly if your robot uses a different domain.
if [[ -n "\${G1_ROS_DOMAIN_ID:-}" ]]; then
  export ROS_DOMAIN_ID="\$G1_ROS_DOMAIN_ID"
else
  unset ROS_DOMAIN_ID
fi
EOF

  chmod +x "$ENV_FILE"
  log "Created $ENV_FILE using interface: $iface"
}

write_launcher() {
  mkdir -p "$BIN_DIR"

  info "Writing $LAUNCH_SCRIPT"
  cat > "$LAUNCH_SCRIPT" <<'EOF'
#!/usr/bin/env bash
# g1_lidar_rviz.sh
#
# Run this after ssh -Y into PC2:
#   ~/bin/g1_lidar_rviz.sh
#
# Optional overrides:
#   G1_LIDAR_TOPIC=/utlidar/cloud ~/bin/g1_lidar_rviz.sh
#   G1_USE_DUMMY_TF=0 ~/bin/g1_lidar_rviz.sh
#   G1_ROS_DOMAIN_ID=10 ~/bin/g1_lidar_rviz.sh

set -Eeuo pipefail

source_relaxed() {
  local had_nounset=0
  [[ $- == *u* ]] && had_nounset=1
  set +u
  # shellcheck disable=SC1090
  source "$1"
  (( had_nounset )) && set -u
}

ENV_FILE="${G1_LIDAR_ENV_FILE:-$HOME/.g1_lidar_env.sh}"
[[ -f "$ENV_FILE" ]] || {
  echo "[ERROR] Missing $ENV_FILE. Run g1_lidar_one_time_setup_pc2.sh first." >&2
  exit 1
}

source_relaxed "$ENV_FILE"

TOPIC="${G1_LIDAR_TOPIC:-/utlidar/cloud_livox_mid360}"
LIDAR_FRAME="${G1_LIDAR_FRAME:-livox_frame}"
MAP_FRAME="${G1_MAP_FRAME:-map}"

# Set to 1 to publish a visualization-only static transform map -> livox_frame.
# This removes RViz's "no tf data" global warning. It is NOT SLAM.
USE_DUMMY_TF="${G1_USE_DUMMY_TF:-1}"

if [[ -z "${DISPLAY:-}" ]]; then
  cat >&2 <<ERR
[ERROR] DISPLAY is empty. RViz needs a GUI display.

Reconnect from your local Ubuntu desktop with:
  ssh -Y dwei@192.168.123.164

Then run:
  ~/bin/g1_lidar_rviz.sh
ERR
  exit 1
fi

# RViz over ssh -Y often needs software rendering.
export LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-1}"

echo "[INFO] DISPLAY=$DISPLAY"
echo "[INFO] Topic=$TOPIC"
echo "[INFO] LiDAR frame=$LIDAR_FRAME"
echo "[INFO] RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-}"
echo "[INFO] ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-<unset/domain 0>}"

# Refresh discovery.
ros2 daemon stop >/dev/null 2>&1 || true
ros2 daemon start >/dev/null 2>&1 || true

echo "[INFO] Waiting briefly for LiDAR topic discovery..."
for i in {1..10}; do
  if ros2 topic list 2>/dev/null | grep -qx "$TOPIC"; then
    echo "[OK] Found topic: $TOPIC"
    break
  fi
  sleep 1
done

if ! ros2 topic list 2>/dev/null | grep -qx "$TOPIC"; then
  echo "[WARN] $TOPIC was not listed by discovery."
  echo "[WARN] RViz may still work if DDS discovery is delayed."
  echo "[WARN] Available lidar/cloud topics:"
  ros2 topic list 2>/dev/null | grep -E 'utlidar|livox|cloud|imu' || true
fi

TYPE="$(ros2 topic type "$TOPIC" 2>/dev/null || true)"
if [[ -n "$TYPE" ]]; then
  echo "[INFO] Topic type: $TYPE"
fi

TF_PID=""
FIXED_FRAME="$LIDAR_FRAME"

if [[ "$USE_DUMMY_TF" == "1" ]]; then
  FIXED_FRAME="$MAP_FRAME"
  echo "[INFO] Starting visualization-only static TF: $MAP_FRAME -> $LIDAR_FRAME"
  ros2 run tf2_ros static_transform_publisher \
    0 0 0 0 0 0 "$MAP_FRAME" "$LIDAR_FRAME" >/tmp/g1_lidar_static_tf.log 2>&1 &
  TF_PID="$!"
fi

cleanup() {
  if [[ -n "${TF_PID:-}" ]]; then
    kill "$TF_PID" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

RVIZ_CONFIG="$(mktemp /tmp/g1_lidar_rviz.XXXXXX.rviz)"

cat > "$RVIZ_CONFIG" <<EOF_RVIZ
Panels:
  - Class: rviz_common/Displays
    Name: Displays
  - Class: rviz_common/Views
    Name: Views
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz_default_plugins/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.03
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: <Fixed Frame>
      Value: true
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Class: rviz_default_plugins/PointCloud2
      Color Transformer: Intensity
      Decay Time: 2
      Enabled: true
      History Length: 5
      Invert Rainbow: false
      Max Color:
        B: 255
        G: 255
        R: 255
      Min Color:
        B: 0
        G: 0
        R: 0
      Name: G1 MID360 PointCloud
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.01
      Style: Points
      Topic:
        Depth: 5
        Durability Policy: Volatile
        History Policy: Keep Last
        Reliability Policy: Best Effort
        Value: $TOPIC
      Use Fixed Frame: true
      Use rainbow: true
      Value: true
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Fixed Frame: $FIXED_FRAME
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz_default_plugins/Interact
    - Class: rviz_default_plugins/MoveCamera
    - Class: rviz_default_plugins/Select
  Transformation:
    Current:
      Class: rviz_default_plugins/TF
  Value: true
  Views:
    Current:
      Class: rviz_default_plugins/Orbit
      Distance: 8
      Focal Point:
        X: 0
        Y: 0
        Z: 0
      Name: Current View
      Pitch: 0.6
      Target Frame: <Fixed Frame>
      Yaw: 0.8
Window Geometry:
  Height: 900
  Width: 1400
EOF_RVIZ

echo "[INFO] Launching RViz. Close the RViz window to stop this script."
echo "[INFO] Fixed Frame in RViz: $FIXED_FRAME"
echo "[INFO] PointCloud2 topic: $TOPIC"

rviz2 -d "$RVIZ_CONFIG"
EOF

  chmod +x "$LAUNCH_SCRIPT"
  log "Created $LAUNCH_SCRIPT"
}

main() {
  info "G1 LiDAR one-time setup/check for PC2"

  need_cmd ip
  need_cmd awk
  need_cmd grep

  if [[ ! -f "/opt/ros/$ROS_DISTRO_NAME/setup.bash" ]]; then
    die "ROS 2 $ROS_DISTRO_NAME not found at /opt/ros/$ROS_DISTRO_NAME/setup.bash. Install ROS Foxy first."
  fi

  sudo_apt_install_missing \
    git curl xauth x11-apps mesa-utils \
    ros-"$ROS_DISTRO_NAME"-rviz2 \
    ros-"$ROS_DISTRO_NAME"-rviz-common \
    ros-"$ROS_DISTRO_NAME"-rviz-default-plugins \
    ros-"$ROS_DISTRO_NAME"-rviz-ogre-vendor \
    ros-"$ROS_DISTRO_NAME"-tf2-ros \
    ros-"$ROS_DISTRO_NAME"-rmw-cyclonedds-cpp \
    ros-"$ROS_DISTRO_NAME"-rosidl-generator-dds-idl \
    python3-colcon-common-extensions \
    libyaml-cpp-dev

  ensure_unitree_ros2_present
  maybe_build_unitree_ws

  local iface="${G1_IFACE:-}"
  if [[ -z "$iface" ]]; then
    iface="$(detect_iface || true)"
  fi

  if [[ -z "$iface" ]]; then
    die "Could not detect robot network interface. Re-run with G1_IFACE=<interface>, e.g. G1_IFACE=eth0 $0"
  fi

  info "Using network interface: $iface"
  ip -o -4 addr show "$iface" || true

  write_env_file "$iface"
  write_launcher

  # Basic validation.
  # shellcheck disable=SC1090
  source_relaxed "$ENV_FILE"

  log "Environment check:"
  echo "  RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-}"
  echo "  CYCLONEDDS_URI=$CYCLONEDDS_URI"
  echo "  G1_LIDAR_TOPIC=$G1_LIDAR_TOPIC"
  echo "  G1_LIDAR_FRAME=$G1_LIDAR_FRAME"

  echo
  info "Current LiDAR/cloud topics visible from this shell:"
  ros2 daemon stop >/dev/null 2>&1 || true
  ros2 daemon start >/dev/null 2>&1 || true
  sleep 2
  ros2 topic list 2>/dev/null | grep -E 'utlidar|livox|cloud|imu' || warn "No lidar/cloud topics discovered yet."

  echo
  log "Done."
  echo "Next time, after ssh -Y into PC2, run:"
  echo "  ~/bin/g1_lidar_rviz.sh"
}

main "$@"
